DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS game_type;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS scorecard;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  handicap REAL
  scorecard
);

CREATE TABLE game (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_id INTEGER NOT NULL,
  date_played DATE NOT NULL,
  score INTEGER NOT NULL,
  FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE game_type (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  description TEXT
);

CREATE TABLE course (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  par INTEGER NOT NULL
);

CREATE TABLE scorecard (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER NOT NULL,
  hole_number INTEGER NOT NULL,
  strokes INTEGER NOT NULL,
  FOREIGN KEY (game_id) REFERENCES game(id)
);

CREATE TABLE team (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_a TEXT UNIQUE NOT NULL,
  team_b TEXT UNIQUE NOT NULL
);